wordpress:
  image:
    repository: wordpress
    tag: 5.8-apache
  replicaCount: 2
  service:
    type: ClusterIP
    port: 80

mariadb:
  image:
    repository: mariadb
    tag: 10.5
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3306
  persistence:
    enabled: true
    size: 8Gi
