---
all:
  children:
    MicroK8S-servers:
      hosts:
        k8s-server-1:
          ansible_host: 158.160.100.135
          ansible_user: ubuntu
    MicroK8S-nodes:
      hosts:
        kubernetes-node-1:
          ansible_host: 158.160.99.79
          ansible_user: ubuntu
        kubernetes-node-2:
          ansible_host: 158.160.121.182
          ansible_user: ubuntu
        kubernetes-node-3:
          ansible_host: 89.169.145.165
          ansible_user: ubuntu
        kubernetes-node-4:
          ansible_host: 158.160.108.244
          ansible_user: ubuntu