{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frontend-backend.fullname" . }}-ingress
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "frontend-backend.fullname" . }}-frontend-service
            port:
              number: {{ .Values.frontend.service.port }}
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ include "frontend-backend.fullname" . }}-backend-service
            port:
              number: {{ .Values.backend.service.port }}
{{- end }}
